name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    env:
      PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - run: npm run check --workspaces
      - run: npm run lint --workspaces
      - run: npm run build --workspaces --if-present
      - run: npx playwright install --with-deps
      - run: npm run test --workspaces
