on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: bun install --frozen-lockfile

      - run: bun run ws codegen
      - run: bun run format
      - run: bun run lint
      - run: bun run ws check
      - run: bun test
      - run: bun run ws build

      - run: npx playwright install --with-deps
      - run: bun run ws e2e

      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref "$SUPABASE_PROJECT_ID"
        env:
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
      - run: supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          DENO_UNSTABLE_SLOPPY_IMPORTS: 1
