on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: bun install --frozen-lockfile

      - run: scripts/bunrunws.sh codegen
      - run: bun run format
      - run: bun run lint
      - run: scripts/bunrunws.sh check
      - run: bun test
      - run: scripts/bunrunws.sh build

      - run: |
          browsers="$(.github/scripts/list_browsers.sh | sort | uniq)"
          npx playwright install $browsers --with-deps
      - run: scripts/bunrunws.sh e2e
