name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    env:
      PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected -t check --parallel=3
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t build --parallel=3
      - run: npx playwright install --with-deps
      - run: npx nx affected -t test --parallel=3 --configuration=ci
