name: Crawl

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - run: |
          echo "SUPABASE_URL=https://${PROJECT_ID}.supabase.co" >> $GITHUB_ENV
      - env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
        run: npx nx run crawler:start
