on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/*.sql'

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: vars.ACT != 'true'
    env:
      SUPABASE_ACCES_TOKEN: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      - run: pip install sqlfluff
      - run: sqlfluff lint .

      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref "$SUPABASE_PROJECT_ID"
        env:
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      - run: supabase db push
