on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/*.sql'
  workflow_dispatch:

env:
  ACT: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install sqlfluff=="$(cat .sqlfluff-version)"
      - run: sqlfluff lint .

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref "${SUPABASE_PROJECT_ID}" <<<"${SUPABASE_DB_PASSWORD}"
        env:
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD : ${{ secrets.SUPABASE_DB_PASSWORD }}
      - run: supabase migration list <<<"${SUPABASE_DB_PASSWORD}"
        env:
          SUPABASE_DB_PASSWORD : ${{ secrets.SUPABASE_DB_PASSWORD }}
      - if: env.ACT != 'true'
        run: supabase migration up --linked --include-all <<<"${SUPABASE_DB_PASSWORD}"
