name: Run Supabase migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/*.sql'

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCES_TOKEN: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase link --project-ref "$SUPABASE_PROJECT_ID"
        env:
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}

      - run: supabase db push
